/* pre_config.h.  Generated by configure.  */
/* pre_config.h.in.  Generated from configure.ac by autoheader.  */

 /* our header */
#ifndef _XFIRE_CONFIG_H
#define _XFIRE_CONFIG_H


/* Define if debugging is enabled. */
/* #undef DEBUG */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define if we've found gaim. */
#define HAVE_GAIM 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Name of package */
/* #undef PACKAGE */

/* Define to the address where bug reports for this package should be sent. */
#define XFIRE_PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define XFIRE_PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define XFIRE_PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define XFIRE_PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define XFIRE_PACKAGE_VERSION ""

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
/* #undef VERSION */

/* Gaim-XFIRE Version */
#define XFIRE_VERSION "0.5.8"


#endif /* _XFIRE_CONFIG_H */

